household:
  displayName: Household
radarr:
  qualityProfileId: 1
  rootFolderPath: "D:\\Movies"
sonarr:
  qualityProfileId: 4
  rootFolderPath: "D:\\TV"
llm:
  maxIters: 8
  providers:
    priority: [openai, openrouter]
    openai:
      chat: gpt-5-mini
      smart: gpt-5
      worker: gpt-5-nano
    openrouter:
      chat: z-ai/glm-4.5-air:free
      smart: z-ai/glm-4.5-air:free
      worker: z-ai/glm-4.5-air:free
tools:
  timeoutMs: 5000
  parallelism: 8
  retryMax: 1
  backoffBaseMs: 80
ux:
  progressThresholdMs: 2500
  progressUpdateIntervalMs: 6000
  progressUpdateFrequency: 3
http:
  connectTimeoutMs: 1500
  readTimeoutMs: 7000
  totalTimeoutMs: 10000
  maxConnections: 128
  retryMax: 1
  backoffBaseMs: 80
cache:
  ttlShortSec: 60
  ttlMediumSec: 300
