household:
  displayName: Household
radarr:
  qualityProfileId: null
  rootFolderPath: null
sonarr:
  qualityProfileId: null
  rootFolderPath: null
llm:
  maxIters: 8
tools:
  timeoutMs: 8000
ux:
  progressThresholdMs: 5000
