household:
  displayName: Household
radarr:
  qualityProfileId: 1
  rootFolderPath: "D:\\Movies"
sonarr:
  qualityProfileId: 4
  rootFolderPath: "D:\\TV"
llm:
  agentMaxIters: 8
  workerMaxIters: 4
  providers:
    priority: [openai, openrouter]
    openai:
      chat:
        model: gpt-4.1-mini
        #easoningEffort: minimal
        params:
          tool_choice: auto
      smart:
        model: gpt-5-mini
        reasoningEffort: medium
        params:
          temperature: 1
          tool_choice: auto
      worker:
        model: gpt-5-mini
        reasoningEffort: minimal
        params:
          temperature: 1
          tool_choice: auto
      quick:
        model: gpt-4.1-nano
        params:
          max_tokens: 180
      summarizer:
        model: gpt-4.1-nano
        #reasoningEffort: minimal
        params:
          max_tokens: 250
          temperature: 0.1
    openrouter:
      chat: z-ai/glm-4.5-air:free
      smart: z-ai/glm-4.5-air:free
      worker: z-ai/glm-4.5-air:free
tools:
  timeoutMs: 1500
  parallelism: 16
  retryMax: 2
  backoffBaseMs: 50
  listMaxItems: 12
  # Optional advanced tuning (used by Agent if present)
  familyParallelism:
    tmdb: 20
    plex: 6
    radarr: 8
    sonarr: 8
  perFamily:
    tmdb:
      timeoutMs: 2500
    plex:
      timeoutMs: 4000
  perTool:
    tmdb_search:
      timeoutMs: 2000
    smart_recommendations:
      timeoutMs: 5000
    intelligent_search:
      timeoutMs: 3000
  hedgeDelayMsByFamily:
    tmdb: 150
  listMaxItemsByFamily:
    tmdb: 6
    plex: 4
  maxToolMessagesInContext: 12
  circuit:
    openAfterFailures: 3
    openForMs: 3000
ux:
  progressThresholdMs: 3000
  progressUpdateIntervalMs: 5000
  progressUpdateFrequency: 4
  heartbeatIntervalMs: 2500
  typingPulseMs: 9000
http:
  connectTimeoutMs: 300
  readTimeoutMs: 900
  totalTimeoutMs: 2200
  maxConnections: 384
  retryMax: 1
  backoffBaseMs: 40
cache:
  ttlShortSec: 60
  ttlMediumSec: 240

discord:
  enabled: false
  botToken: ""
  channelId: ""
  webhookUrl: ""
  sendToolEvents: true
  sendThinking: true
