household:
  displayName: Household
radarr:
  qualityProfileId: 1
  rootFolderPath: "D:\\Movies"
sonarr:
  qualityProfileId: 4
  rootFolderPath: "D:\\TV"
llm:
  maxIters: 8
  providers:
    priority: [openai, openrouter]
    openai:
      chat:
        model: gpt-5-mini
        reasoningEffort: minimal
      smart:
        model: gpt-5
        reasoningEffort: medium
      worker:
        model: gpt-5-nano
        reasoningEffort: medium
      quick:
        model: gpt-5
        params:
          max_tokens: 180
      summarizer:
        model: gpt-5-nano
        reasoningEffort: high
        params:
          max_response_tokens: 200
    openrouter:
      chat: z-ai/glm-4.5-air:free
      smart: z-ai/glm-4.5-air:free
      worker: z-ai/glm-4.5-air:free
tools:
  timeoutMs: 2500
  parallelism: 10
  retryMax: 1
  backoffBaseMs: 80
  listMaxItems: 8
ux:
  progressThresholdMs: 2500
  progressUpdateIntervalMs: 6000
  progressUpdateFrequency: 3
http:
  connectTimeoutMs: 1500
  readTimeoutMs: 2000
  totalTimeoutMs: 5000
  maxConnections: 128
  retryMax: 1
  backoffBaseMs: 80
cache:
  ttlShortSec: 60
  ttlMediumSec: 300
