household:
  displayName: Household
radarr:
  qualityProfileId: 1
  rootFolderPath: "D:\\Movies"
sonarr:
  qualityProfileId: 4
  rootFolderPath: "D:\\TV"
llm:
  agentMaxIters: 5
  workerMaxIters: 2
  providers:
    priority: [openai, openrouter]
    openai:
      chat:
        model: gpt-5-mini
        reasoningEffort: low
        params:
          temperature: 1
          tool_choice: auto
      smart:
        model: gpt-5-mini
        reasoningEffort: medium
        params:
          temperature: 1
          tool_choice: auto
      worker:
        model: gpt-5-mini
        reasoningEffort: low
        params:
          temperature: 1
          tool_choice: auto
      quick:
        model: gpt-4.1-nano
        params:
          max_tokens: 180
      summarizer:
        model: gpt-5-nano
        reasoningEffort: low
        params:
          max_response_tokens: 200
          temperature: 1
    openrouter:
      chat: z-ai/glm-4.5-air:free
      smart: z-ai/glm-4.5-air:free
      worker: z-ai/glm-4.5-air:free
tools:
  timeoutMs: 1800
  parallelism: 12
  retryMax: 2
  backoffBaseMs: 60
  listMaxItems: 12
ux:
  progressThresholdMs: 600
  progressUpdateIntervalMs: 900
  progressUpdateFrequency: 2
http:
  connectTimeoutMs: 300
  readTimeoutMs: 900
  totalTimeoutMs: 2200
  maxConnections: 384
  retryMax: 1
  backoffBaseMs: 40
cache:
  ttlShortSec: 45
  ttlMediumSec: 150
