household:
  displayName: Household
radarr:
  qualityProfileId: 1
  rootFolderPath: "D:\\Movies"
sonarr:
  qualityProfileId: 4
  rootFolderPath: "D:\\TV"
llm:
  maxIters: 8
tools:
  timeoutMs: 8000
  parallelism: 4
  retryMax: 2
  backoffBaseMs: 200
ux:
  progressThresholdMs: 2000
  progressUpdateIntervalMs: 2000
  progressUpdateFrequency: 4
http:
  connectTimeoutMs: 3000
  readTimeoutMs: 10000
  totalTimeoutMs: 15000
  maxConnections: 100
cache:
  ttlShortSec: 60
  ttlMediumSec: 300
