household:
  displayName: Household
radarr:
  qualityProfileId: 1
  rootFolderPath: "D:\\Movies"
sonarr:
  qualityProfileId: 4
  rootFolderPath: "D:\\TV"
llm:
  agentMaxIters: 5
  workerMaxIters: 2
  providers:
    priority: [openai, openrouter]
    openai:
      chat:
        model: gpt-5-mini
        reasoningEffort: low
      smart:
        model: gpt-5-mini
        reasoningEffort: minimal
      worker:
        model: gpt-5-mini
        reasoningEffort: medium
      quick:
        model: gpt-4.1-nano
        params:
          max_tokens: 180
      summarizer:
        model: gpt-5-nano
        reasoningEffort: low
        params:
          max_response_tokens: 200
    openrouter:
      chat: z-ai/glm-4.5-air:free
      smart: z-ai/glm-4.5-air:free
      worker: z-ai/glm-4.5-air:free
tools:
  timeoutMs: 2500
  parallelism: 10
  retryMax: 2
  backoffBaseMs: 80
  listMaxItems: 25
ux:
  progressThresholdMs: 600
  progressUpdateIntervalMs: 1200
  progressUpdateFrequency: 2
http:
  connectTimeoutMs: 300
  readTimeoutMs: 1000
  totalTimeoutMs: 2500
  maxConnections: 256
  retryMax: 1
  backoffBaseMs: 40
cache:
  ttlShortSec: 30
  ttlMediumSec: 120
