household:
  displayName: Household
radarr:
  qualityProfileId: null
  rootFolderPath: null
sonarr:
  qualityProfileId: null
  rootFolderPath: null
llm:
  maxIters: 8
tools:
  timeoutMs: 8000
  parallelism: 4
  retryMax: 2
  backoffBaseMs: 200
ux:
  progressThresholdMs: 5000
http:
  connectTimeoutMs: 3000
  readTimeoutMs: 10000
  totalTimeoutMs: 15000
  maxConnections: 100
cache:
  ttlShortSec: 60
  ttlMediumSec: 300
